### ISSUE TITLE
Set autoStart feature dynamicolly

### ISSUE THREAD

**Issue by sionnaouattara** [BrianRosamilia/vue-crono#10]
Hi, think you for your great Job.
I would like to know how to set dynamically a cron feature "autoStart".
Thinks

**Comment by BrianRosamilia** [comment]
Unfortunately, you'd need to use a higher order component to do this :( 

https://pusher.com/tutorials/higher-order-components-vue

This isnt so simple in Vue.  This is just a fact of life with how I implemented this functionality.  Thanks for the compliment btw ! :)

**Comment by Pyro979** [comment]
@sionnaouattara why not have it be set to autoStart false, but then dynamically start it if needed?

**Comment by BrianRosamilia** [comment]
Yeah true that's actually way better.  Set autoStart: false and start it on mounted based on some condition.  Even easier.  Good job @Pyro979

**Comment by sionnaouattara** [comment]
Thanks for answering me so soon.  For the moment i switch between autStart
true and autStart false to manage my features. Good job

Le mer. 13 mai 2020 à 22:45, BrianRosamilia <notifications@github.com> a
écrit :
