### ISSUE TITLE
Defining crons with out starting them

### ISSUE THREAD

**Issue by Pyro979** [BrianRosamilia/vue-crono#2]
I think it would be handy to be able to define crons that start out stopped. 

```javascript
        cron:[{
            time: 5000,
            method: 'load',
        },
        {
            time: 1000,
            method: 'loadFaster',
            started: false,
        },
        {
            time: 32000,
            method: 'stopTimer'
        }]
```

**Comment by BrianRosamilia** [comment]
It's a good idea, I'll probably add it as `autostart: false` by default.  I'll work on it shortly :)

**Comment by BrianRosamilia** [comment]
Sorry for the delay, I just added this to `1.1.2` under the option `autoStart` which defaults to `true`!  Thanks for your help
