### ISSUE TITLE
Not currently possible to have the same method defined twice

### ISSUE THREAD

**Issue by Pyro979** [BrianRosamilia/vue-crono#3]
Use case: 
Ping method - have a regular ping every minute, and a "slow" ping every 5 minutes. and being able to switch between them based on my logic by stopping one and starting another. Current workaround: create a different method to alias the original method.

**Comment by BrianRosamilia** [comment]
I'd have to introduce a way to identify individual jobs pointing to the same method, thus making the package a bit more complicated :( I think think the workaround of having two separate methods is actually cleaner for both you and the package tbh

I'd actually really enjoy adding something like this fully integrated into the library ( it would make your use case a lot easier imo https://www.npmjs.com/package/backoff ) (although if you're using custom logic to decide when to 'back off' then maybe it doesnt cover this case)

Curious what you think!

**Comment by Pyro979** [comment]
i get trying to keep it slow. I think my particular use case could easily be solved if you implement #4. I'm gonna make comment there about my use case.

**Comment by BrianRosamilia** [comment]
We decided to close this but I'll keep in mind having some useful `backoff` methods for varying timings
