### ISSUE TITLE
import 1.1.2 error

### ISSUE THREAD

**Issue by wanggenyou** [BrianRosamilia/vue-crono#7]
import Vue from 'vue'
import crono from 'vue-crono'
Vue.use(crono)

package.json
"vue": "^2.5.17",
"vue-crono": "^1.1.2",

ERROR:
This relative module was not found:
* ./cleanTime.vue in ./node_modules/vue-crono/index.js

**Comment by BrianRosamilia** [comment]
That didn't actually work because .vue + commonjs aren't compatible anymore.  I fixed this in 1.1.4 

thanks for the report 🥇

**Comment by BrianRosamilia** [comment]
@wanggenyou I'm sorry for the trouble you had but I believe this is now fixed after trying it myself with 1.1.4

Let me know if this isn't the case!

**Comment by wanggenyou** [comment]
problem is solved
